iminuit/_libiminuit.pyx
=> Fixed bug. RunTimeError -> RuntimeError

iminuit/util.py
just fixed a small bug found for new versions of python.
=> fixed import of StringIO

iminuit/_libiminuit.pyx
Fix for Issue #151. It was an indentation problem.
=> Fix docstring formatting.

.travis.yml, Makefile, doc/conf.py, doc/installation.rst
This fixes a Sphinx build issue we've had for a long time.
I first thought its a real Sphinx or matplotlib plot directive issue, that's why I filed an issue here:
https://github.com/matplotlib/matplotlib/issues/6233
(read that if you're interested what the issue and fix are).
Here I fix the issue and also update the install docs how building the Sphinx docs works.
=> Fix Sphinx build

setup.py
=> fixed issue 213

Minuit/inc/Minuit2/MinimumBuilder.h, Minuit/inc/Minuit2/MnApplication.h, Minuit/inc/Minuit2/MnMigrad.h
Patch syncs our ROOT with upstream ROOT
=> sync with upstream ROOT version

.gitignore, README.rst, doc/about.rst, doc/api.rst, doc/changelog.rst, doc/conf.py, doc/contribute.rst, doc/index.rst, doc/install.rst, doc/tutorials.rst, environment-dev.yml, requirements.txt
This is a major docs update.
The user install isntructions are now much simpler, and several other pages have been added.
@HDembinski - Please have a look.
I would like to merge this later today, and then continue on more docs improvements in follow-up PRs.
One thing I had planned to do here is to rewrite the dev docs page.
=> Major docs update

iminuit/tests/test_iminuit.py
This adds an explicit test for numpy-based gradient function, showing that this works.
=> added a test for numpy-based grad function

iminuit/_libiminuit.pyx, iminuit/py23_compat.py, iminuit/tests/test_iminuit.py
We want moar tests.
Addresses #242, #241, #239.
=> Addresses missing test coverage

iminuit/_libiminuit.pyx
=> Change to Py2/3 compatible code in iminuit/_libiminuit.pyx

iminuit/PythonCaller.h, iminuit/Utils.h, iminuit/tests/test_iminuit.py
with tests to make sure it does not go by unnoticed anymore
=> fix for segfault when PythonCaller throws

iminuit/_libiminuit.pyx
The implementation of matrix() in 1.3 was completely wrong when parameters were fixed. It was reading uninitialized memory. I am not quite sure why the tests did not catch this, as this is tested. Perhaps the test was too simple to show these issues.
=> fix broken matrix implementation

iminuit/tests/test_iminuit.py
the new test would have triggered the bug that PR #284 has fixed
=> better test of matrix() with fixed params

iminuit/PythonCaller.h
When user functions raises an exception, report that original exception in addition to the extra information added by the C++ code.
=> Python error report

iminuit/_minimize.py
@HDembinski - Small fix suggested by static code analysis here: https://lgtm.com/projects/g/iminuit/iminuit/snapshot/57d9e0298e6450e41f9eb30f69dd4a5422e62b67/files/iminuit/_minimize.py?sort=name&dir=ASC&mode=heatmap&showExcluded=false#L49
=> Remove duplicated constraints check from minimize

iminuit/Minuit2Struct.pxi, iminuit/_libiminuit.pyx, iminuit/tests/is_ipython_notebook.ipynb, iminuit/tests/test_frontend.py, iminuit/util.py, test_notebooks.py
=> Fix auto frontend for ipython shell

.travis.yml
* consistently test python 3.7 and 2.7
* don't run do superfluous runs of the test suite
* conda build test does not work and I could not get it to work despite trying, remove it
The conda build is tested by conda-forge. It makes no sense to test it here.
=> cleanup of travis and removal of broken conda build test

iminuit/Minuit2.pxi, iminuit/_libiminuit.pyx
Reverts scikit-hep/iminuit#327
=> Revert "replacing auto_ptr with unique_ptr"

.travis.yml, ci-scripts/install_pypy.sh, iminuit/PythonCaller.h, iminuit/tests/test_describe.py, iminuit/tests/test_iminuit.py, setup.py
=> PyPy compat

.travis.yml
This PR adds a CI test for Gammapy.
See https://github.com/scikit-hep/iminuit/issues/337#issuecomment-493412424
=> Add CI test with Gammapy

.ci/azure-wheel-helpers/build-wheels.sh, .ci/azure-wheel-helpers/macos-install-python.sh
This should fix the wheelbuilding.
=> Fix building wheels with Python 3.8

iminuit/_libiminuit.pyx, iminuit/_minuit_methods.py, iminuit/tests/test_plot.py
=> Fix issue #378

.ci/azure-pipeline-build.yml, .ci/azure-pipeline-test.yml, MANIFEST.in, setup.cfg
=> SDist testing

iminuit/_libiminuit.pyx, iminuit/_minimize.py, iminuit/tests/test_functions.py, iminuit/tests/test_iminuit.py, iminuit/tests/test_plot.py, iminuit/tests/test_repr.py
**new**
ngrads
**replaced, old form deprecated**
get_fmin() -> fmin
get_param_states() -> params
get_initial_param_states() -> init_params
get_num_call_fcn() -> ncalls_total
get_num_call_grad() -> ngrads_total
migrad_ok() -> valid
**deprecated**
edm
=> replacing methods with properties

Makefile, src/iminuit/_minuit_methods.py, src/iminuit/pdg_format.py, src/iminuit/repr_html.py, src/iminuit/repr_text.py, src/iminuit/tests/test_pdg_format.py, src/iminuit/tests/test_repr.py
=> Pdg format

src/iminuit/_libiminuit.pyx
=> fix: Allow subclasses to use from_array_func

src/iminuit/_libiminuit.pyx, src/iminuit/tests/test_iminuit.py
=> fix for broken np_merrors when parameters are fixed

src/iminuit/repr_html.py, src/iminuit/tests/test_repr.py
=> dark theme friendlier html style

src/iminuit/Minuit2Struct.pxi, src/iminuit/_libiminuit.pyx, src/iminuit/repr_text.py, src/iminuit/tests/test_iminuit.py, src/iminuit/tests/test_repr.py
Attempt to fix https://github.com/scikit-hep/pyhf/issues/1069
=> Restore try harder feature

Makefile, setup.cfg, src/iminuit/_minimize.py, src/iminuit/_minuit.py, src/iminuit/repr_text.py, src/iminuit/util.py, tests/test_minuit.py, tests/test_repr.py, tests/test_util.py
Minuit.ncalls_total -> Minuit.nfcn
Minuit.ngrads_total -> Minuit.ngrad
removed FMin.ncalls_total, FMin.ngrads_total
=> Clean more counter interface

src/iminuit/_minuit.py, tests/test_minuit.py
=> fix for segfault when hesse is called with all parameters fixed

tests/test_minuit.py
=> test minos with new min

src/iminuit/util.py, tests/test_util.py
=> allow parameter names in slices

doc/changelog.rst, src/iminuit/minimize.py, tests/test_minimize.py
=> support simplex, stra option, better message

.gitignore, src/iminuit/minuit.py, src/iminuit/util.py, tests/test_util.py
As described in #625, this PR seeks to add the ability to access a subset of the ValueView (and other views) using a list/tuple of names/indices.
=> Enable BasicView __getitem__ with tuple/list

.pre-commit-config.yaml, src/iminuit/cost.py, src/iminuit/experimental.py, src/iminuit/util.py, tests/test_experimental.py, tests/test_util.py, tutorial/generic_least_squares_function.ipynb
=> replace merge_func_code with merge_signatures, add make_func

src/iminuit/util.py, tests/test_util.py
=> fix slicing

src/iminuit/util.py, tests/test_util.py
make_with_signature failed when called twice in a row on a function without a code object.
=> fix make_with_signature

doc/changelog.rst, src/iminuit/version.py, src/minimumstate.cpp, tests/test_minimize.py, tests/test_minuit.py
=> fix FMin error state when Hesse runs into call limit

doc/changelog.rst, src/iminuit/cost.py, src/iminuit/minuit.py, src/iminuit/version.py, tests/test_minuit.py
Closes #669 
This also makes it possible to run `mncontour` with an external minimum point.
=> Fix mncontour

CMakeLists.txt, src/iminuit/version.py
Hesse Patch: https://github.com/root-project/root/pull/8176
=> Update Root to latest master + Hesse Fix

.github/workflows/test.yml, .github/workflows/wheels.yml, doc/changelog.rst
Added aarch64 test and  wheel build support.
Related to #676 . @HDembinski, Could you please review this PR?
=> Add aarch64 test and  wheel build support

.gitignore, doc/changelog.rst, src/iminuit/minuit.py, tests/test_draw.py
Remove location argument again which does not work as intended
=> improve draw tests and minor improvement to draw_mncontour

cmake_ext.py, doc/changelog.rst, src/iminuit/version.py
Credit to @tdegeus, see https://github.com/pybind/cmake_example/pull/58 and https://github.com/conda-forge/iminuit-feedstock/pull/62.
=> fix: support cross-compiling with Conda

doc/tutorial/conditional_variable.ipynb, doc/tutorials.rst, setup.cfg
=> add tutorial on conditional variable

pyproject.toml
=> Fix binary numpy downloads on test venvs

pyproject.toml
Committed via https://github.com/asottile/all-repos
=> wheel not required for setuptools PEP 517 (all-repos)

src/iminuit/cost.py, tests/test_cost.py
LeastSquares now supports multivariate models.
=> support multivariate functions in cost.LeastSquares

src/iminuit/util.py, tests/test_util.py
Added Matrix.to_dict() for symmetry with BasicView.to_dict(). Closes #721
=> added Matrix.to_dict

doc/notebooks/cost_functions.ipynb, doc/notebooks/memory_layout.ipynb, doc/studies.rst, setup.cfg
Include tutorials for multivariate fits.
=> update cost function tutorial

src/iminuit/cost.py, tests/test_cost.py
Closes #770 
The clumsy updater mechanism is replaced by an idiomatic solution, which fixes pickling support. Pickling is now explicitly tested for all builtin cost functions.
=> fix pickling of all builtin cost functions

src/iminuit/util.py, tests/test_util.py
=> make FixedView act as mask for other views

.pre-commit-config.yaml, Makefile, pyproject.toml, setup.cfg, src/iminuit/cost.py, src/iminuit/minuit.py, src/iminuit/util.py, tests/test_cost.py
This fixes a lot of typing issues and a few edge cases where typing checks indeed found a bug in the code (where it was not doing what was advertised).
=> fix typing issues and enable mypy in pre-commit

src/iminuit/minuit.py
=> fix corner case treatment of linear constraint

tests/test_minuit.py
Add some extra checks in response to #809 but no bug was found.
=> add more checks for gradients

src/iminuit/cost.py, tests/test_cost.py
=> add configurable number of bins for extended/unbinnedNLL

pyproject.toml
=> Specifiy minimum required numpy version

doc/notebooks/basic.ipynb, pyproject.toml, src/iminuit/cost.py
Explain how to use annotations in the basic tutorial and in docstring of cost.py.
=> Better docs for limits from annotated model parameters

src/iminuit/minuit.py, tests/test_minuit.py
Adds an alternative experimental algorithm for mncontour in addition to calling MnContour, which sometimes produces bad contours. The new algorithm is found to produce contours where MnContour fails, but is slower.
=> experimental mncontour algorithm

src/iminuit/cost.py, tests/test_cost.py
These are trivial to compute for a LeastSquares function, but adding these methods for symmetry with BinnedCost functions is good.
=> Add LeastSquares.pulls and LeastSquares.prediction

doc/notebooks/basic.ipynb
Fix #882
Fixes (some) typos in basic.ipynb
=> fix-typo-in-basic

doc/bibliography.txt, doc/faq.rst, doc/notebooks/basic.ipynb, doc/notebooks/interactive.ipynb, src/iminuit/minuit.py, src/iminuit/util.py, tests/test_minuit.py
Closes #881 
With `Minuit.fixto`, you can fix a parameter and assign a value with one call, instead of calling `Minuit.fixed` and `Minuit.values`.
=> Add Minuit.fixto

pyproject.toml, tests/test_draw.py
=> skip test_interactive and friends when ipywidgets is not installed

src/iminuit/util.py
Newly introduced bug in C++ Minuit resolved with workaround in iminuit so that our tests still pass.
=> update to latest root

.pre-commit-config.yaml, doc/notebooks/basic.ipynb
Add more comments about confidence intervals, after an email exchange with Yu Lu.
=> improve comments on coverage

pyproject.toml
Quick fix for an issue I noticed.
=> Improve maintainer metadata

src/iminuit/minuit.py
=> fix: add readout_format to slider

src/iminuit/cost.py
Found the missing line needed to address #1058
=> fix NormalConstraint not appearing in docs

.github/workflows/coverage.yml, .github/workflows/test.yml, src/iminuit/cost.py, src/iminuit/minuit.py, tests/test_cost.py
=> Improve minos cl docstring

src/iminuit/_repr_html.py
resolved #1088 
below is an example
=> Add warning styles for parameter limits in params function
