scikit-hep/iminuit

iminuit/tests/test_describe.py, iminuit/util.py
Make python 2 and python 3 compatibility much easier to achieve.
=> Get rid of StringIO altogether

iminuit/_libiminuit.pyx, iminuit/tests/test_functions.py, iminuit/tests/test_iminuit.py
The [iminuit.Minuit.np_matrix](http://iminuit.readthedocs.org/en/latest/api.html#iminuit.Minuit.np_matrix) member function is broken:
```
def np_matrix(self, correlation=False):
"""Error or correlation matrix in numpy array format."""
import numpy as np
#TODO make a not so lazy one
return np.array(matrix)
```
I'll fix it and add tests.
=> Fix Minuit.np_matrix

Minuit/src/GenAlgoOptions.cxx, Minuit/src/MnLineSearch.cxx, README.rst, iminuit/frontends/__init__.py, setup.py
two explicit includes were needed in the Minuit source.
The encoding at the top of setup.py needs to be "utf-8" with a hyphen, not without, in order to run at all on windows python 3.5.
I removed the import of html.py in `frontends/__init__.py`, as per #166 
And I fixed a couple of typos in the readme, and added explicit mention of the dependency on cython.
=> small changes needed to compile on windows, python 3.5, plus typo fixes in README

iminuit/frontends/html.py
I've modified the HTML printout a little bit. This is an example from the tutorial.
Before:
After:
I think it looks cleaner. What do you think?
=> Use general format for parameter printout in place of exponent notation

.gitignore, .travis.yml, MANIFEST.in, Makefile, README.rst, doc/api.rst, doc/index.rst, doc/installation.rst, doc/references.txt, iminuit/__init__.py, iminuit/_libiminuit.pyx, iminuit/_plotting.py, iminuit/frontends/html.py, iminuit/tests/cyfunc.pyxbld, iminuit/tests/test_describe.py, iminuit/tests/test_frontend.py, iminuit/tests/test_functions.py, iminuit/tests/test_iminuit.py, iminuit/tests/test_latex.py, iminuit/tests/test_plot.py, iminuit/tests/test_util.py, iminuit/tests/utils.py, iminuit/util.py, setup.py
=> Use setuptools and pytest

iminuit/Minuit2.pxi, iminuit/PythonFCNBase.h, iminuit/PythonGradientFCN.h, iminuit/_libiminuit.pyx, iminuit/tests/test_iminuit.py
This PR addresses #125 and #175 and adds the `grad_fcn` keyword  argument when initialising `Minuit`.
Example usage:
```python
def f(x, y, z):
return 0.2 * (x - 2.) ** 2 + 0.1 * (y - 5.) ** 2 + 0.25 * (z - 7.) ** 2 + 10
def f_grad(x, y, z):
dfdx = 0.4 * (x - 2.)
dfdy = 0.2 * (y - 5.)
dfdz = 0.5 * (z - 7.)
return (dfdx, dfdy, dfdz)
m = Minuit(f, grad_fcn=f_grad)
m.migrad()
```
=> Add support for supplying the gradient function to minuit

iminuit/frontends/console.py, iminuit/latex.py, iminuit/tests/test_latex.py
Fixes #191.
I haven't added a test for the console bug fix. There don't appear to be any existing tests for the console tables, so rather than writing a lonely test I skipped it.
=> Support empty parameter lists in table-building

iminuit/_plotting.py
The v array used to label the contours. It was not in sync with the bound argument of the call to self.contour(...) which generates the contours. This is now fixed.
=> fixed failing test_drawcontour

.gitignore, Makefile, setup.py
These patches make development more fluid and convenient. These are all backward-compatible improvements with no changes to users. All warnings should be gone now, if you use gcc or clang.
`make` now runs `make build`, not `make help`, which is most commonly what you want when you type `make`. I set the dependencies of the `build` target properly, so that the module is correctly rebuild when the sources change. This was not the case before.
I found a recipe on the internet to make setuptools use compiler-specific flags. This allows me to add flags for gcc and clang to ignore warnings in code generated by Cython and in the externally developed Minuit code. As it is, we cannot fix these warnings, they need to be fixed in the Cython code generator and the original Minuit source code. This is …
=> Build improvements

Makefile
Forgot to put the correct paths. It works without, but `make` runs some superfluous commands if the dependencies are set incorrectly.
=> dependency fix, improves performance

README.rst
fix for the appveyor badge which should point to the correct build now
=> fix for appveyor badge

iminuit/frontends/console.py
- removed what looks like accidental debug prints
- added a header explaining that the matrix shown is a correlation matrix and not the covariance matrix
=> improvement of console frontend

iminuit/_libiminuit.pyx, iminuit/tests/test_iminuit.py
Addresses issue #200 
The tuple-based attribute interface `values`, `errors`, `merrors`, and `covariance` is mirrored by numpy-friendly getters with the `np_` prefix. This adds a great deal of convenience for numpy users.
=> numpy getters

Makefile, doc/conf.py
A "doc" rule was advertised in the "help", but not actually implemented. Now we have one, and it only rebuild the html docu if the source files changed.
I took the liberty to remove the "doc-show" rule, which only works on Mac.
Finally, I added a bit of code to doc/conf.py, which enables sphinx to find the locally build iminuit module. When you are developing, that is usually what you want. Before, you had to install iminuit at least user-wide just to generate the docs.
=> added missing doc rule; removed doc-show rule; make sphinx find local build

iminuit/_libiminuit.pyx, iminuit/tests/test_describe.py, iminuit/tests/test_iminuit.py, iminuit/util.py
`describe` did not fail on functions with variable length args, while it should. Since it did not raise an error, Minuit later fails with an obscure error message when you try to call `migrad`.
Now an error is correctly raised by `describe` and the cases are tested.
=> fix: detect and handle functions with variable length args

.travis.yml, Makefile, setup.py
This is a fix for #234. Instead of just throwing an error, display a helpful error message if cython is not available. Also fixes installation of iminuit without Cython if the pregenerated cpp file is actually there. This used to work and got broken. We need this for the next release.
=> Fix cython dep

iminuit/Minuit2Struct.pxi, iminuit/_libiminuit.pyx, iminuit/frontends/console.py, iminuit/frontends/frontend.py, iminuit/frontends/html.py, iminuit/py23_compat.py, iminuit/tests/test_frontend.py, iminuit/tests/test_iminuit.py, iminuit/tests/test_latex.py, iminuit/tests/test_minimize.py, iminuit/tests/test_util.py, iminuit/tests/utils.py, iminuit/util.py
This became another large patch, because I wanted to fully test any impact of what I did to `get_param_states`.
At the core, this patch removes `get_initial_param_state` and adds an optional keyword `initial` to `get_param_states`. If you call `get_param_states(initial=True)`, you get the initial parameter state, so exactly what `get_initial_param_state` was supposed to do.
I removed the two internal methods `_prepare_initial_param` and `_prepare_param`. The latter was identical to `get_param_states`. The former turned out to produce an inconsistent struct under certain conditions. I reimplemented the function in a consistent way.
Then I added unit tests for both versions of `get_param_states`. The method is also used by the frontends to print output on the console and in IPython, so I …
=> Issue 163 get initial param state

iminuit/tests/test_plot.py
Cython coverage (#158) shows that this function isn't covered by a test:
https://github.com/iminuit/iminuit/blob/04fcc8af160c423f7c778b48cc41ff423925f5f7/iminuit/_libiminuit.pyx#L1205
https://github.com/iminuit/iminuit/blob/04fcc8af160c423f7c778b48cc41ff423925f5f7/iminuit/_libiminuit.pyx#L1233-L1236
@HDembinski - You or me?
=> Add test for draw_profile

.travis.yml, Makefile, doc/contribute.rst, test_notebooks.py
If we keep notebooks, I think we should test them in CI.
Otherwise it's very hard to maintain the content, even for a stable package like this one.
See #15. I'll keep that closed, because that was a very old attempt to implement that. By now the Jupyter tooling is better. Assigning this to myself under the v1.3 milestone.
=> Test notebooks in CI

iminuit/Minuit2.pxi, iminuit/_libiminuit.pyx, iminuit/tests/test_iminuit.py, test_notebooks.py
Addresses #230 #105 
It is one of the key features of Minuit is that you can modify the parameter state. A common approach is to fix some parameters initially, then minimize only free parameters, then release all parameters and fit all together. Example:
```
m = Minuit(some_func, x=1, y=2, fix_y=True)
m.migrad()  # fit only x
m.fixed['y'] = False
m.migrad()  # resume fit, now with floating y
```
So far this was not possible, because there was no way to interact with the parameter state in Minuit. The proposed workaround was to create a new `Minuit` instance. This was not intuitive for many people, and actually a step back from precursors like pyminuit, which allowed to modify the fit state.
So I fixed this by changing the classes that are returned when you call `Minuit.args`, …
=> Modify parameter state

doc/about.rst, doc/changelog.rst, doc/index.rst
Looks like we don't have a changelog for iminuit yet.
I think it's very valuable to have, just a new page in the docs with a short bullet list of major changes.
Like e.g. the update to a new version of MINUIT, or the recent numpy methods that were added.
We can just start with v1.3, and add a dummy entry for v1.2 with the date and saying that before that no changelog was kept.
@HDembinski - May I interest you in this, or should I make a PR?
=> Add changelog

.travis.yml, Makefile, README.rst, doc/index.rst, iminuit/__init__.py, iminuit/tests/test_frontend.py, iminuit/tests/test_iminuit.py, iminuit/tests/test_plot.py, setup.py, status.rst, test_notebooks.py
@HDembinski - here's the local fails I got when running from the `sdist` for `test_console` and `test_cython_embedsig`: https://gist.github.com/cdeil/ea3bbea7f5a72b474e1bbba27c24ec42
This should be understood / fixed before making a release.
The first step should be to add a CI test that builds and tests the sdist on travis-ci and appveyor, with Python 2 and 3. That's the main thing that needs to work, not just from the dev folder. Maybe some current builds can be removed.
I see this one:
https://github.com/iminuit/iminuit/blob/3f98a13a2caf908f21c087c4c29044921eafa193/.travis.yml#L25-L26
but it's not even running the tests currently:
https://travis-ci.org/iminuit/iminuit/jobs/400390456#L1043
=> Add CI that builds and tests sdist

Makefile, iminuit/PythonCaller.h, iminuit/Utils.h, iminuit/tests/test_iminuit.py, iminuit/util.py
This is now really fixed and works in Python-2.7 and Python-3.7. Tests check that the original error message is included.
=> fixing exception report for python 2 and python 3

.travis.yml
Add Python 3.6 runtime to the Travis CI testing suite.
=> Add Python 3.6 runtime test to Travis CI

.travis.yml
This PR drops the use of the unsupported Travis `sudo` API. In [November 2018 Traivs announced they would be retiring the 'sudo' API](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration).
> If you currently specify sudo: false in your .travis.yml, we recommend removing that configuration soon.
=> Remove unsupported Travis sudo API

setup.cfg, setup.py
This adds the [recommended method](https://docs.pytest.org/en/latest/goodpractices.html#integrating-with-setuptools-python-setup-py-test-pytest-runner) of integrating PyTest with setup.py.
It also drops the redundant 'setuptools' from install_requires; setuptools must be available already for the file to run at all; PEP 518's `pyproject.toml` is the only way to change what happens before setup.py runs (and only for pip).
=> Better pytest integration

.ci/azure-build-pipeline.yml, .ci/azure-publish-dist.yml, .ci/azure-setup.yml, .ci/azure-steps.yml, .ci/build-wheels.sh, .ci/macos-install-python.sh, dev-requirements.txt
This adds an Azure pipeline build, producing wheels and an sdist (with latest Cython). I'll need to set up the release pipeline as well to send these to PyPI, but that's entirely external. It will also be a manual step for now, rather than happening automatically on release tags. See the latest build here: https://dev.azure.com/scikit-hep/iMinuit/_build/results?buildId=786 . Closes #334 .
Minor cleanup on Travis (Python 3.7 was released, for example). The GammaPy test won't pass yet, obviously. PyTest integration and testing was slightly adjusted for consistency.
=> Adding azure

setup.cfg
Use the new directory ignore pattern of `check-manifest` introduced in [`v0.42`](https://github.com/mgedmin/check-manifest/blob/master/CHANGES.rst#042-2020-05-03).
> You can ignore directories only by ignoring every file inside it. You can use `--ignore=dir/**` to do that
This fixes the issue in CI that has been seen in the [Azure Pipelines](https://dev.azure.com/scikit-hep/iMinuit/_build?definitionId=10&_a=summary) since the `check-manifest` `v0.42` release.
=> fix: Use check-manifest v0.42 directory ignore pattern

README.rst, binder/postBuild, setup.cfg
Resolves #396 
Requires PR #398 to go in first.
Add [Binder](https://mybinder.org/) support by using the [`postBuild`](https://mybinder.readthedocs.io/en/latest/config_files.html#postbuild-run-code-after-installing-the-environment) configuration file to install the required dependencies of `requirements-dev.txt` and then install `iminuit` itself from source. Additionally, add a launch Binder badge to the README that launches into the `tutorial` directory.
[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/scikit-hep/iminuit/docs/add-Binder-support?filepath=tutorial)
=> Add Binder support

src/iminuit/tests/test_describe.py, src/iminuit/util.py
Following #463, this PR introduces a fix to `describe` in order to recognize the signature of wrapped functions.
=> Fix describe for wrapped functions

src/iminuit/_libiminuit.pyx, src/iminuit/tests/test_iminuit.py
@matthewfeickert @kratsg This patch makes the iteration ("try hard") feature of iminuit configurable. You should definitely try to play with the precision keyword, too, because I did and it improve convergence when the cost function has low precision (the doc string was extended to better explain what this setting does).
=> make iterate configurable

.ci/install_pypy36.py, .pre-commit-config.yaml, doc/conf.py, setup.py, src/iminuit/_deprecated.py, src/iminuit/_minuit.py, src/iminuit/repr_html.py
Trying out PyUpgrade to clean up older syntax to cleaner 3.6+. Idea from @kratsg & @matthewfeikert in https://github.com/scikit-hep/pyhf/pull/1164 .
Only the first commit is hand written - the second commit is entirely generated.
- style: add pyupgrade
- style: pre-commit run -a
=> style: pyupgrade

src/iminuit/_minuit.py, tests/test_minuit.py
globalcc is the correlation of the internal covariance matrix, which is redundant at best and possibly misleading when parameters are limited
=> Remove globalcc

MANIFEST.in
The SDist does not contain the tests. While the _wheel_ should not contain tests (and I didn't check to verify that by adding it, `/tests` is not picked up as a package or as package data, which you should do), it is helpful if the SDist contains tests, so you can build and then verify the build worked, say in conda-forge. I'll look at a different way to solve this on conda-forge, but this is a suggestion.
Edit: from a very quick check, it looks fine. It's rare to have `/src/<package>` based packages accidentally pick up `/tests` in the wheel.
=> tests: include tests in SDist

src/fcn.cpp, src/type_caster.hpp, src/usercovariance.cpp, src/userparameterstate.cpp
A fix for https://github.com/scikit-hep/pyhf/pull/1208, but also allows us to convert more efficiently in the future
=> use custom type_caster for std::vector

README.rst
Suggested changes to the badges:
* Add one for conda-forge
* ~~Include the badges in the PyPI readme, as most of them are very useful there too.~~
~~If you want only one of the two changes, feel free to ask or change it.~~
I've dropped the change to the inclusion marker for now, but I highly recommend adding the badges to the Read the Docs / PyPI readme, as they provide a very dense and graphical information display that is useful.
=> docs: add conda-forge badge

src/iminuit/util.py, tests/test_describe.py, tests/test_minuit.py
More information on this can be found in issue #608.
I'm happy for any feedback regarding the fix :)
Added some tests in both `tests/test_describe.py` as well as `tests/test_minuit.py`.
=> Fix iminuit.util.describe(callable) for partial functions without signature

doc/changelog.rst, src/iminuit/util.py, src/iminuit/version.py, tests/test_util.py, tutorial/generic_least_squares_function.ipynb
Since probfit is depracated, it would make sense (imho) to include this useful bit of code 
here, just like decribe() and make_func_code().
It makes it much easier to construct cost functions from compound objects.
I have added an example to:
generic_least_squares_function.ipynb
=> Port of merge_func_code functionality from probfit to iminuit

src/iminuit/minuit.py
Plotting the error as an area can expand the plot if the requested span is smaller than the errors.
Fixed by respecting the axes limits.
=> Fix: adjust limits in `draw_profile`

src/iminuit/util.py, tests/test_util.py
The new version of ValueView's `__iter__` now only iterates over the values, instead of keys & values. This is nice for converting to numpy arrays but removes the ability to convert to a dict with `dict(m0.values)`. This PR adds a `to_dict` method to `BasicView` to conveniently convert views to a dict.
Relevant historic discussion: https://github.com/scikit-hep/iminuit/issues/272#issuecomment-403433623
=> Add to_dict method to BasicView

doc/changelog.rst, src/iminuit/util.py, src/iminuit/version.py, tests/test_describe.py, tests/test_experimental.py, tests/test_util.py, tutorial/basic_tutorial.ipynb
Closes #625 at the cost of changing the output type of describe back from tuple to list
This is patching two things. Firstly, `describe` is now again returning a list (as it used to in v1.x), which works better with the extended indexing capabilities of ValueView and Matrix. Secondly, Matrix now handles slices and selections in a special way so that you get the right submatrix. Example code:
```py
c1 = LeastSquares(...) # parameters a, b
c2 = LeastSquares(...) # parameter b, c
m = Minuit(c1 + c2, ...)
c1args = describe(c1)
value_only_ab = m.values[c1args]
cov_only_ab = m.covariance[c1args] # this now returns the correct square matrix
```
=> describe returns list; util.Matrix supports special selection

CITATION.rst
Just saw that one ',' is missing in the BibTeX example entry, after trying to copy it.
=> fixed missing ',' in iminuit BibTeX.

.github/workflows/wheels.yml
Updating for the new location as part of the Python Packaging Authority!
=> chore: pypa/cibuildwheel

doc/changelog.rst, src/iminuit/cost.py, src/iminuit/util.py, tests/test_cost.py
Numba accelerated functions are now only called if the model returns arrays of type float32 or float64. The code falls back to Numpy for anything else.
Closes #658
=> support float128 in builtin cost functions

doc/changelog.rst, src/hesse.cpp, src/iminuit/minuit.py, tests/test_core.py, tests/test_minuit.py
Closes #631
This is a minor breaking change in the API.
If the user calls `Minuit.hesse` without an existing FunctionMinimum, a FunctionMinimum is now created. If MnHesse fails, we do not raise an exception anymore, since the information about the failure can be read from the `Minuit.fmin` attribute.
=> fixes for calling hesse and minos without existing function minimum

.github/workflows/wheels.yml, cmake_ext.py, doc/changelog.rst, pyproject.toml, src/iminuit/version.py
- chore: sync with cmake_example
I've made this look a bit more like `pybind/cmake_example` (and made `cmake_example` look a bit more like this in https://github.com/pybind/cmake_example/pull/53, as well) - the more this looks like the maintained example, the better. I've tried not to lose anything that was was an intentional change from that example, like the usage of ninja on Windows, etc. I've also kept f-strings and Paths, anything that was clearly an improvement over the original (and I think we are likely about to remove Python 2/3.5 from our examples, so likely it will look even more similar in the future).
@HDembenski, if you don't like any changes, I can roll back any of them expect the key change that allows Apple Silicon to be supported. :)
- ci: build Apple Silicon wheels
I've …
=> chore: add Apple Silicon wheels

.pre-commit-config.yaml
The pip-installable PyPI package is 1-2 MB, and has cibuildwheel wheels for all major platforms. It allows exact pinning of pre-commit versions rather than depending on what you have installed locally, and works on pre-commit.ci, allowing automatic fixes. It also comes with a pre-commit hook.  See https://github.com/ssciwr/clang-format-wheel or https://twitter.com/HenrySchreiner3/status/1442877941910802433?s=20 for my announcement. Versions 10, 11, and 12 are available.
=> chore: use PyPI package for clang-format

.pre-commit-config.yaml
The old name still works, of course, but we were asked to rename it to follow convention and so we did. Here’s the new name. Follow up to #688.
=> clang-format hook renamed

src/iminuit/minuit.py
Closes #702 and fixes the CI on the other PRs. Matplotlib now uses closed polygons instead of unclosed lines for contours.
=> fix: support MPL 3.5+

.github/workflows/test.yml, .github/workflows/wheels.yml, pyproject.toml, setup.cfg
I've added 3.10 & musllinux (and probably PyPy 3.8 binaries too, forgot to check to see if PyPy binaries are included). Manylinux2010 is produced on 3.6-3.9, and 2014 for 3.10, just like NumPy. @HDembinski, is there a way to trigger the wheel build without an upload to make sure it works?
Also bumped the CI to include 3.10 final.
=> include binaries for Python 3.10, musllinux

Makefile, setup.cfg
Two quick cleanups I noticed while working on recent PRs.
The Makefile can be made a bit cleaner now that python2 is no longer supported. I'd recommend looking into nox, as well; it can be much more reproducible, handing virtual environments for you. (I also hate make, so I'm biased).
I also ran into a problem with Sphnix - this pins 4.1.0 exactly, which doesn't support Python 3.10, so I couldn't build docs. You probably intended `==4.1.*`, but that's still not ideal; the 4.1 series is  not an LTS, so things like Python 3.10 support are not backported to it. I would either use `~=4.1`, which will allow 4.1 or newer, but not 5, or I'd use >=4.1, which is what I did here - [Pinning is generally a misused and terrible practice](https://iscinumpy.dev/post/bound-version-constraints). But up to …
=> clean makefile, unpin 4.1.0 for sphinx

bench/cost.json, bench/plot_cost.py, bench/test_cost.py, src/iminuit/cost.py, tests/test_cost.py
The keyword `log` was added to the `UnbinnedNLL` and `ExtendedUnbinnedNLL` to support models which return the logpdf instead of the pdf.
Some pdfs that we use are of the exponential family (normal, exponential, poisson, Crystal Ball, ...), which means that one can implement the `logpdf` for those directly, which is not only more efficient, but also expected to be numerically more stable than effectively doing `log(exp(logpdf))`.
Some benchmarks were added to explore the benefits of this change, which are currently not part of the documentation, but will be included in a future update.
=> Support logpdf

src/iminuit/cost.py, tests/test_cost.py
The classes UnbinnedNLL and ExtendedUnbinnedNLL already supported fits to multivariate data, but this ability was not documented and not tested. This patch adds test and documentation of this feature.
=> Support multivariate data in *UnbinnedNLL

src/iminuit/util.py, tests/test_cost.py
iminuit raises an ZeroDivisionError when ndof is zero when printing the FMin object when the reduced chi2 is computed. This is not sensible, the sensible thing is to return nan in this case, so that's what this patch does.
=> fix ndof zero

README.rst, pyproject.toml, setup.cfg, src/iminuit/_deprecated.py, src/iminuit/util.py, tests/test_deprecated.py, tests/test_minuit.py, tests/test_util.py
jacobi.propagate supersedes util.propagate, so util.propagate is deprecated.
Also fixes `make_with_signature` to always use the slow path. The fast path does not work on some functions. The exact conditions when it fails are not clear.
Use numpy.VisibleDeprecationWarning instead of warnings.DeprecationWarning and turn warnings during tests into failures.
=> Deprecate util.propagate

MANIFEST.in
Fixes conda-forge (and any other downstream packagers running tests)
I think only html files were added?
We should add the check-manifest check, as described in the Scikit-HEP developer guidelines.
=> Missing test files in SDist

src/iminuit/minuit.py, tests/test_draw.py, tests/test_minuit.py
Closes #745 
This adds the `grid` keyword for Minuit.profile, Minuit.mnprofile, Minuit.contour. It allows users to select the points where the profile or mnprofile or contour should be evaluated.
Minuit.contour now also accepts two sizes for its `size` keyword, which are then used for each parameter, respectively.
A bug in Minuit.contour was fixed. The contour was plotted rotated by 90 degrees before.
=> support custom grid in profile, mnprofile, contour; fix bug in draw_contour

src/functionminimum.cpp, tests/test_core.py, tests/test_issue.py
Closes #694
This is fixes a bug in upstream Minuit2. When the EDM value is NaN, Minuit2 wrongly reports that the EDM value is below the threshold and claims that the minimum is valid. This patch fixes the issue in the class FunctionMinimum, which is good, but a deeper issue remains: MnMigrad does not handle NaNs correctly.
This also updates ROOT to master + my outstanding ROOT patches.
=> workaround for FMin.is_valid

CMakeLists.txt
This enables packagers (conda-forge, in this case) to use their own packaged version of pybind11. For conda-forge, this will enable iminuit to particle in ABI binning migrations that we've recently developed (pybind11's ABI hasn't changed in two years, but an ABI bump is coming). It also enables quicker response if there's an issue such as in https://github.com/conda-forge/iminuit-feedstock/pull/76.
This is _optional_ and orthogonal to #742 (which is also needed - iminuit segfaults on PyPy 3.9 without it). If you do not expect anyone to use the binary ABI of iMinuit _and_ you want to fully control the exact pybind11 version, then you don't need to go for this option. I think iMinuit would have use for the binary ABI. Boost-histogram does not. Awkward might (it originally would have, not …
=> External pybind11 option (such as in conda-forge)

pyproject.toml
Editted: I mistook the usage of tool.nbqa.mutate black=1 to mean that the notebooks were supposed to be black formatted. Instead, I'm now just removing that old setting (which is deprecated, since black now natively supports jupyter notebook formatting).
=> Removed unused and deprecated Black notebook config

.pre-commit-config.yaml, setup.cfg
Main update is flake8, which was pointing at the old gitlab mirror, rather than the proper repo. Also moved the check (non-mutating checks should be after mutating ones like black).
- Update flake8 config (github, bump, move to after mutating checks)
- Minor pybind11 bump (fixes issues with the new PyPy 3.9)
=> Minor updates (pybind11 segfault on pypy 3.9, flake8 broken mirror)

src/iminuit/minuit.py, tests/test_minuit.py
Common cl values like 0.68, 0.9, 0.95, 0.99 in `Minuit.minos` and `Minuit.mncontour` can now be used without having `scipy` installed. Moreover, values larger than 1 are interpreted as sigmas, so that it is possible to compute 1,2,3,... sigma intervals.
=> handle common cl values and test api when scipy is missing

tests/test_cost.py
The numpy.float128 is not present on some platforms (e.g. i386).
To match the C++ type "long double", numpy.longdouble should be
used instead.
Fixes bug #753
=> Skip tests that use numpy.float128 type if it not available

src/fcn.cpp, src/iminuit/__init__.py, src/iminuit/minuit.py, src/iminuit/testing.py, tests/test_draw.py, tests/test_issue.py, tests/test_minuit.py, tests/test_repr.py, tests/test_scipy.py, tests/test_tabulate.py
This removes the warning when a cost function does not provide an attribute called `errordef`. Instead, all functions without `errordef` are treated as if they are chi2-like.
=> make errordef=1 the default

src/iminuit/minuit.py, src/iminuit/util.py, src/iminuit/version.py, tests/test_minuit.py
- The internal guess for `Minuit.errors` is to use a fraction of the value. If the value is negative, the error was initialized to a negative value. This patch fixes that mistake.
- Non-positive values assigned to `Minuit.errors` are now rejected. A warning is raised and the invalid value is replaced by the internal heuristic.
=> fix bug in error heuristic and prevent assigning non-positive values

src/iminuit/minuit.py, src/iminuit/version.py, tests/test_minuit.py
`Minuit.mncontour` now appends the first point to the end to close the contour, so that it is easier to plot
=> close mncontour for convenience

.gitignore, doc/notebooks/basic.ipynb, doc/notebooks/interactive.ipynb, doc/plots/interactive.py, src/iminuit/cost.py, src/iminuit/minuit.py, src/iminuit/util.py, tests/test_draw.py
See #767
- Minuit.interactive
- Added Fix and Opt toggle buttons for each parameter. If Fix is toggled, clicking on Fit will not change this parameter, but the slider is still enabled. If Opt is toggled, the corresponding slider gets disabled and its value will be chosen by Minuit so that it minimizes the cost function.
- Keyword arguments are now forwarded to the plot function, which defaults to the visualize method of the cost function. Use this to adjust the visualization.
- Added Reset button
- Added Dropdown menu to select fitting algorithm
- Added parameter `model_points` to method `visualize` of `UnbinnedNLL`, `ExtendedUnbinnedNLL`, `LeastSquares` to change how many points are generated for the model
=> Enhance interactive

src/iminuit/minuit.py, tests/test_draw.py
Closes #774 and adapts to new deprecations/changes in Scipy-1.9.0
=> Fix for Minuit.interactive when using an array-based function

Makefile, doc/conf.py, doc/reference.rst, src/iminuit/minimize.py
Closes #775
The docs now show `iminuit.minimize` instead of `iminuit.minimize.minimize` in the reference, consistent with `iminuit.Minuit` instead of `iminuit.minuit.Minuit`. The formatting of the docstring for `minimize` was improved.
=> Improve docs

src/iminuit/util.py, tests/test_util.py
Broadcasting support for BasicView. Allows for example `np.all(m.fixed == False)`
=> Comparison with broadcast

.github/dependabot.yml
Many of the actions are quite out of date; using dependabot (and I've set a monthly setting to keep the number of updates down) would really help keep the actions fresh & active. See most of the other scikit-hep repos for examples of working dependabot files. Dependabot recently became smart enough to only do "matching" updates; v2 -> v3 and not v3.0.1 or something like that.
=> Add dependabot to keep actions up to date

.github/workflows/coverage.yml, .github/workflows/docs.yml, .github/workflows/pre-commit.yml, .github/workflows/release.yml, .github/workflows/test.yml, pyproject.toml, setup.cfg
Updating to add Python 3.11. For the moment, this adds all three OS's for 3.11, can be scaled back when the PR tests pass.
FYI, trying to roll out 3.11 support in Hist and iminuit's a testing dependency.
=> Add Python 3.11, drop 3.6

.github/workflows/test.yml
Committed via https://github.com/asottile/all-repos
=> ci: update to Python 3.11 final release

src/iminuit/cost.py
Adds a public interface to get the template prediction out of the Template class. You need this if you want to plot the template yourself.
=> Template prediction

src/iminuit/cost.py
All binned likelihoods now have a public method called `prediction` which returns the expected count for each bin.
=> prediction for all binned likelihoods

src/iminuit/minuit.py
Found the typo in the online documentation.
My only question is whether I should reflow the paragraph,  because my typo fix resulted in a line length of 90 instead, whereas most lines seem to be 88 chars long. However I installed pre-commit and surprisingly the commit passed the checks, therefore I didn't bother, also in the interest of keeping the diff trivial.
=> Fix typo "probility"→ "probability" in minos docstring

doc/install.rst
Use 'req@url' syntax when using pip to install from a remote git repository over 'url#egg=req' to avoid the use of #egg= fragments with a non-PEP 508 name. This will be required in pip v25.0+.
- c.f. https://github.com/pypa/pip/pull/11617 for more details
=> docs: Use 'req@url' syntax to install from remote VCS

src/iminuit/util.py, tests/test_describe.py
Close #846 
The fix ignores string annotations unless they match those in annotated-types (which are duplicated in iminuit.typing).
=> Fix string annotations

src/iminuit/cost.py, tests/test_cost.py
Under certain circumstances, class Template modified the template input arrays *inplace*, which should not happen.
This fixes the bug and adds a test that exposed the bug.
Thanks to @zjkjsd who reported this in #825
=> fix template input modification bug in Template class

Makefile, src/iminuit/minuit.py, tests/test_draw.py, tests/test_minuit.py
Allow using positional integers in addition to variable names in Minuit.minos, Minuit.profile, Minuit.mnprofile, Minuit.contour, Minuit.mncontour, and the corresponding Minuit.draw_X methods.
=> Integer as variable

src/iminuit/cost.py, tests/test_cost.py, tests/test_minuit.py
Hello @HDembinski
This PR is regarding https://github.com/scikit-hep/iminuit/issues/791
=> improve error message for cost function

src/iminuit/minuit.py, tests/test_without_matplotlib.py
Closes #866 
If matplotlib is not installed, `Minuit._repr_html_()` now quietly skips plotting the figure. The generated figure is now really part of the html code returned by this method.
=> Ignore missing matplotlib when calling Minuit._repr_html_()

src/iminuit/cost.py, tests/test_cost.py
`bins` is the standard keyword in numpy, matplotlib.
=> Rename keyword nbins to bins in UnbinnedCost.visualize

src/iminuit/minuit.py, src/iminuit/util.py, tests/test_util.py
Closes #901
The private function `iminuit.util._jacobi` is removed without deprecation. It was internally replaced by `scipy.optimize.approx_fprime`. Those who used `_jacobi` for some reason should switch to `jacobi.jacobi` from the `jacobi` package if a high-accuracy derivative is required or use `scipy.optimize_approx_fprime` for a low-accuracy derivative.
=> Fix tests on FreeBSD, remove util._jacobi

.gitignore, pyproject.toml
This reduces the size of the SDist from 160 MB to 2.2 MB (mostly docs, notebooks, and tests, I expect). (Previously this was done at https://github.com/scikit-hep/iminuit/blob/v2.21.3/MANIFEST.in)
=> fix: SDist size reduction

tests/test_cost.py
Fixes the following warning:
```
=============================== warnings summary ===============================
tests/test_cost.py::test_UnbinnedNLL_visualize[False]
tests/test_cost.py::test_UnbinnedNLL_visualize[True]
/tmp/autopkgtest-lxc.hry0h8si/downtmp/autopkgtest_tmp/tests/test_cost.py:244: VisibleDeprecationWarning: keyword 'nbins' is deprecated, please use 'bins'
c.visualize((1, 2), nbins=20)
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
====== 597 passed, 2 skipped, 5 xfailed, 1 xpassed, 2 warnings in 17.25s =======
```
=> test_cost: use pytest.warns instead of raises for VisibleDeprecationWarning

src/iminuit/cost.py, tests/test_cost.py
Closes #913 see that issue for a detailed analysis by @stephanlachnit why the original naive code did not work everywhere.
Maybe this is related to #902, too.
@stephanlachnit Could you please check whether this fix indeed solves the issue? I cannot run tests on the affected systems.
=> fix safe_log on systems which use 32 bit floats

src/iminuit/cost.py
Fixes the bug that CostSum.visualize prints two figures and the wrong aspect ratio of the figure.
=> fix CostSum.visualize bug

pyproject.toml, src/iminuit/typing.py, src/iminuit/util.py, tests/test_describe.py
This adds support for the Interval annotation type that is in the package `annotated_types` and `pydantic`, which was previously missing. It also adds tests for float annotations from `annotated_types` and `pydantic`, to check that they are correctly handled by `util.describe`
=> Support Interval type and check compatibility with pydantic

doc/reference.rst, src/iminuit/minuit.py
The method `Minuit.draw_mnmatrix` shows 2D contours that do not align with the 1D intervals, which is ok. The keyword `cl` sets the confidence level for the 1D intervals and 2D contours, according to Wilks' theorem, the projections of the 2D contours are then wider than the 1D intervals. The docstrings make this point more clear.
=> Clarify meaning of 2D contours in Minuit.draw_mnmatrix

src/iminuit/util.py, tests/test_issue.py, tests/test_util.py
Closes #923 
The smart sampling algorithm was not tested on step functions and was broken when applied to such functions. The fix is to stop iterating when an interval becomes too narrow. In addition, further stopping criteria were added, based on number of iterations and time spend.
=> Iteration limit in smart sampling to fix behavior for step functions

CMakeLists.txt, bench/plot.ipynb, doc/_static/interactive_demo.ipynb, doc/notebooks/automatic_differentiation.ipynb, doc/notebooks/basic.ipynb, doc/notebooks/binned_vs_unbinned.ipynb, doc/notebooks/conditional_variable.ipynb, doc/notebooks/cost_function_benchmarks.ipynb, doc/notebooks/cost_functions.ipynb, doc/notebooks/cython.ipynb, doc/notebooks/error_bands.ipynb, doc/notebooks/external_minimizer.ipynb, doc/notebooks/generic_least_squares.ipynb, doc/notebooks/gof.ipynb, doc/notebooks/hesse_and_minos.ipynb, doc/notebooks/interactive.ipynb, doc/notebooks/memory_layout.ipynb, doc/notebooks/numba.ipynb, doc/notebooks/roofit.ipynb, doc/notebooks/roofit/rf101_basics.ipynb, doc/notebooks/roofit/rf109_chi2residpull.ipynb, doc/notebooks/scipy_and_constraints.ipynb, doc/notebooks/simultaneous_fits.ipynb, doc/notebooks/template_fits.ipynb, doc/notebooks/template_gof.ipynb, doc/notebooks/template_model_mix.ipynb
WIP, Adding debug info on failures.
=> fix: include debug info on failures

.github/dependabot.yml, bench/plot.ipynb
Reduces dependabot spam, and actually helps with linked actions (like upload/download artifact v4 not being compatible with v3).
See https://github.com/scientific-python/cookie/pull/348.
=> ci: group dependabot updates

src/iminuit/util.py
=> improve docs for make_with_signature

src/iminuit/cost.py, tests/test_cost.py
Closes #966 
`LeastSquares.model` can now be used to uniformly call models which accept parameter values and parameter arrays in the same way, as already indicated by the docstring.
=> fix LeastSquares.visualize for models that accept parameter array

CMakeLists.txt, src/type_caster.hpp
Closes #976 
This fixes an ODR violation and adds more warnings regarding ODR violations to the standard build flags (which are treated as errors).
=> check for odr violations and fix odr violation

.github/workflows/test.yml, doc/notebooks/correlated_data.ipynb
Committed via https://github.com/asottile/all-repos
GitHub is doing a staged rollout of `macos-latest` pointing at `macos-14`, which is an ARM based runner and only supports Python 3.10+. This locks in the Intel runner (until GitHub eventually removes them).
Edit: GitHub has just shipped macos ARM Python 3.8 & 3.9, so when the staged rollout hits this repo, it might still working. I'll try explicitly using the new runners to test.
=> ci: macos-latest is changing to macos-14 ARM runners

.github/workflows/release.yml, .pre-commit-config.yaml
* Add generation of GitHub artifact attestations to built sdist and wheel before upload.
c.f.:
- https://github.blog/2024-05-02-introducing-artifact-attestations-now-in-public-beta/
- https://docs.github.com/en/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds
* Update `python-jsonschema/check-jsonschema` pre-commit hook to recognize `attestations` `permissions` key.
=> ci: Add GitHub artifact attestations to package distribution

pyproject.toml, src/iminuit/_deprecated.py, src/iminuit/_exceptions.py, src/iminuit/cost.py, src/iminuit/typing.py, src/iminuit/util.py, tests/test_cost.py, tests/test_deprecated.py, tests/test_describe.py, tests/test_minuit.py, tests/test_util.py
- `describe` now also recognizes `Annotated[float, (a, b)]` as the limit (a, b) for the parameter.
- added convenience types: PositiveFloat, Probability under iminuit.typing
- Replaced VisibibleDeprecationWarning with FutureWarning
- Upgraded _deprecated
=> fix for VisibleDeprecationWarning, useful annotated types, support tuple annotation

noxfile.py, pyproject.toml, src/iminuit/cost.py, tests/test_cost.py
Closes #941 
So far the iminuit.cost functions only support models that pass each parameter as a positional argument. This makes it difficult to use models whose number of arguments should be easy to vary.
To make working with the latter easier, the cost functions now support models with a variable number of arguments in the form `def model(x, *par)`. The actual number of arguments and their names are then passed with the new keyword `name`, which can also be used to override the model parameter names found by inspecting the model signature.
=> Add name argument to all cost functions

pyproject.toml
This is used, but not declared. So many packages depend on this that it's being always pulled in for testing, but in a minimal environment it's missing.
See https://github.com/pyodide/pyodide/pull/4767#issuecomment-2291397326.
=> fix: missing dependency on packaging

CMakeLists.txt
This is a small PR to configure the CMake 3.18+ `FindPython` mode for `pybind11` to let it use the CMake search methods, in order to avoid having to pass the older `Python_ROOT_DIR`/`Python_INCLUDE_DIR` methods.
I'm not sure if anything else needs to be configured further – the selected `nox` sessions all pass on my machine locally and the recipe builds successfully within a Pyodide Docker container with this patch applied.
- This came up in https://github.com/pyodide/pyodide/pull/4767
- See also: https://github.com/pyodide/pyodide/discussions/2186
=> Set `PYBIND11_FINDPYTHON` `ON` to use `FindPython` CMake mode

.ci/release_check.py, doc/update_changelog.py, pyproject.toml, python_releases.py, src/iminuit/_deprecated.py, src/iminuit/_parse_version.py, src/iminuit/minuit.py, tests/test_deprecated.py, tests/test_parse_version.py
We promise to only depend on numpy, so let's remove the packaging dependency, which is used only for parsing version strings. Correct parsing of version strings is surprisingly complicated, and I could not find a standard lib function to do this. Fortunately, we do not need to support [the full spec](https://packaging.python.org/en/latest/specifications/version-specifiers/).
=> remove packaging dependency

.gitignore, CMakeLists.txt, src/application.cpp, src/contours.cpp, src/fcn.cpp, src/fcn.hpp, src/functionminimum.cpp, src/functionminimum_extra.cpp, src/functionminimum_pickle.cpp, src/hesse.cpp, src/lasymmatrix.hpp, src/lavector.hpp, src/machineprecision.cpp, src/main.cpp, src/migrad.cpp, src/minimumstate.cpp, src/minos.cpp, src/minuitparameter.cpp, src/print.cpp, src/printimpl.cpp, src/pybind11.hpp, src/scan.cpp, src/simplex.cpp, src/strategy.cpp, src/usercovariance.cpp, src/userparameterstate.cpp, src/usertransformation.cpp
Closes #976 
One could expose the issue (before the fix) on macOS after installing gcc-14 with homebrew with the command
`CXX=gcc-14 python -m build -w`
=> Fix ODR issue in type_caster which could result in UB when `-flto` is enabled

doc/conf.py, doc/release.md, doc/root_version.py, pyproject.toml
We opt for a manual update strategy for the ROOT version, because it changes slowly and an efficient way to do it automatically in CI is elusive. Instructions were added to the release.md instructions and conf.py in the doc folder.
Since the ROOT repo is huge, we want to make shallow clones for git submodules, but then we cannot determine the relation of the commit to the closest tag, because that history which connects tag and commit is not there. Checking out all tags with `git pull --tags` takes a lot of bandwidth, and is not enough. We also need to check out the history between the latest tag and the commit. We don't know which tag the commit is closest to, so the best way would be to iteratively load the most recent history until the commit is connected to a tag.
=> Fix ROOT version in docs

.github/workflows/release.yml, .github/workflows/test.yml, pyproject.toml, src/main.cpp
Adding 3.13 wheels. ~~Doesn't add free-threaded wheels yet.~~ Remove outdated skips for NumPy.
Close #1044.
=> ci: add 3.13 wheels

.github/workflows/coverage.yml, .github/workflows/docs.yml, .github/workflows/release.yml, .github/workflows/test.yml
This exists now, and doesn't produce a notice on each job warning about "latest".
=> ci: use official GHA for uv

pyproject.toml
A few things I noticed that can be updated. Modern version of ruff can auto-detect `src` layout. scikit-build-core 0.10+ can read the min version from the `build-system.requires` table.
=> chore: some minor updates

pyproject.toml
Before moving to scikit-build-core, this was the contents of the `License` field. Putting the entire contents of the license file here breaks `importlib.metadata.metadata("iminuit")` (see https://github.com/python/cpython/issues/119650), and isn't needed - the license file is stored in the wheel already, and the currently only canonical location for license metadata is the trove classifiers. PEP 639, which is currently provisionally accepted and waiting support in packaging, PyPI, etc, solves this by supporting SPDX license expressions. But that's not ready yet.
(This is not critical, but a minor annoyance I hit while debugging)
=> fix: use old license text

.pre-commit-config.yaml, src/iminuit/minuit.py, tests/test_scipy.py
The various SciPy minimizers have different options that can be adjusted to change and improve performance. Presently, the iminuit API does not allow passing options to these minimizers, which limits their usefulness for some minimization problems (specifically mine). I added a parameter to minuit.scipy() to allow passing options to scipy.optimize.minimize(). It keeps the existing default options that were being passed and allows for these defaults to be overwritten by the user.
=> Add ability to pass options to SciPy minimizers

pyproject.toml, src/iminuit/qtwidget.py, tests/qtwidget_example.py
Closes #1074 
The layout was changed so the parameters always take the minimal space. Font size was reduced to 11pt. The size of the result area was increased so that the full result can be seen on Windows.
The layout was not made user-adjustable, because parameters, buttons, and the result have fixed sizes anyway, so the only area with an adjustable size is the plot.
The code was simplified in a couple of places and some blocks refactored to functions to improve clarity.
Minimum and maximum values for each slider are taken from the Minuit.limits.
=> Fix Qt widget sizing issues and simplify code

.github/workflows/coverage.yml, .github/workflows/test.yml, src/iminuit/cost.py, tests/test_cost.py
=> Fix LeastSquares visualize on unsorted x-values

.github/workflows/release.yml, noxfile.py, pyproject.toml
A little modernization, but mostly adding the missing 313t classifier to build free-threading wheels. If #1099 is merged first, this should be rebased, otherwise that one should be rebased. Also 314t should be added.
=> Add free-threading wheels (missing!)
